nfs-driver:
  privileged: true
  image: rancher/storage-nfs:v0.1.1
  pid: host
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  environment:
    NFS_SERVER: '${NFS_SERVER}'
    MOUNT_DIR: '${MOUNT_DIR}'
    MOUNT_OPTS: '${MOUNT_OPTS}'
  volumes:
  - /run:/run
  - /dev:/host/dev
  - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
  metadata:
    storage_driver:
      name: rancher-nfs
      scope: environment
      volumeAccessMode: multiHostRW
