ebs-driver:
  privileged: true
  net: host
  image: rancher/storage-ebs:v0.0.2
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  environment:
    AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
    AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
  volumes:
  - /run:/run
  - /dev:/host/dev
  metadata:
    storage_driver:
      name: rancher-ebs
      scope: environment
      volumeAccessMode: singleHostRW
